CREATE TABLE IF NOT EXISTS orders (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  description  TEXT
);

CREATE TABLE IF NOT EXISTS billing_entities (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  description  TEXT
);

CREATE TABLE IF NOT EXISTS billing_records (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  description  TEXT,
  order_id   INT REFERENCES orders (id),
  entity_id   INT REFERENCES billing_entities (id)

);



