spring.application.name=order_processing
spring.kafka.bootstrap-servers=kafka-demo-24927.germanywestcentral.azurecontainer.io:9092
spring.kafka.consumer.group-id=myGroup

#spring.kafka.properties.schema.registry.url=localhost:8081
spring.data.elasticsearch.cluster-name=docker-cluster
spring.data.elasticsearch.cluster-nodes=elastic-demo-25762.germanywestcentral.azurecontainer.io:9200
spring.data.elasticsearch.repositories.enabled=true
spring.kafka.consumer.properties.spring.json.trusted.packages=*

database=postgres
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://demo-app-pg.postgres.database.azure.com/postgres}
spring.datasource.username=postgres_admin
spring.datasource.password=observability4dev!
spring.sql.init.mode=always
logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=INFO