CREATE TABLE IF NOT EXISTS addresses (
     id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     address     TEXT NOT NULL,
     city        TEXT NOT NULL,
     state       TEXT NOT NULL,
     zip_code    TEXT NOT NULL,
     country     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS shipping_records (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_uid  UUID NOT NULL,
    order_id          INT REFERENCES orders (id),
    shipped_at        TIMESTAMP,
    delivery_status   TEXT,
    carrier           TEXT,
    delivery_estimate TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tracking_records (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipping_record_id INT REFERENCES shipping_records (id),
    address_id        INT REFERENCES addresses (id),
    tracking_number   TEXT,
    status            TEXT,
    updated_at        TIMESTAMP
);



